/*
Nama : Rafli fairuz pramudya
Nim : 2501082012
Tanggal : 25-Juni-2026
Program : Form Penggajian Karyawan
 */
package Pratikum250626;

import javax.swing.JOptionPane;

/**
 *
 * @author rafli
 */
public class FromPenggajianKaryawan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromPenggajianKaryawan.class.getName());

    /**
     * Creates new form FromPenggajianKaryawan
     */
    public FromPenggajianKaryawan() {
        initComponents();
      
       txtGp.setEditable(false);
       txtUpj.setEditable(false);
       txtTuph.setEditable(false);
       txtTgj.setEditable(false);
       txtPjk.setEditable(false);
       txtGb.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGolongan = new javax.swing.ButtonGroup();
        lblPenggajian = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        lblGol = new javax.swing.JLabel();
        cbGol = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblGp = new javax.swing.JLabel();
        lblUpj = new javax.swing.JLabel();
        lblTuph = new javax.swing.JLabel();
        lblTgj = new javax.swing.JLabel();
        lblPjk = new javax.swing.JLabel();
        lblGb = new javax.swing.JLabel();
        txtGp = new javax.swing.JTextField();
        txtUpj = new javax.swing.JTextField();
        txtTuph = new javax.swing.JTextField();
        txtTgj = new javax.swing.JTextField();
        txtPjk = new javax.swing.JTextField();
        txtGb = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPenggajian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPenggajian.setText("FORM PENGGAJIAN KARYAWAN");

        lblNama.setText("Nama");

        lblNik.setText("NIK");

        lblJam.setText("Jam Kerja");

        lblGol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGol.setText("Golongan");

        cbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih golongan", "golongan 1", "golongan 2", "golongan 3", "golongan 4" }));
        cbGol.addActionListener(this::cbGolActionPerformed);

        btnHitung.setText("Hitung Gaji");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblGp.setText("Gaji Pokok");

        lblUpj.setText("Upah/Jam");

        lblTuph.setText("Total Upah");

        lblTgj.setText("Total Gaji");

        lblPjk.setText("Pajak");

        lblGb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGb.setText("Gaji Bersih");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("~~Transkripsi Gaji Karyawan ~~");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnHitung)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblGb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNik, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblJam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTuph, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTgj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblPjk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpj, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(txtNik))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblGol, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPenggajian)
                                    .addComponent(txtGp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTuph, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTgj, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGb, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPjk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpj, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPenggajian)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNik)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJam)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGp)
                    .addComponent(txtGp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpj)
                    .addComponent(txtUpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTuph)
                    .addComponent(txtTuph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTgj)
                    .addComponent(txtTgj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPjk)
                    .addComponent(txtPjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGb)
                    .addComponent(txtGb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGolActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        String nama = txtNama.getText();
        String nik = txtNik.getText();
        String jam = txtJam.getText();
        if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Data nama tidak boleh kosong");
            txtNama.requestFocus();
            return;
        }
        if(nik.isEmpty()){
             JOptionPane.showMessageDialog(this, "Data Nik tidak boleh kosong");
             txtNik.requestFocus();
             return;
        }
        if(jam.isEmpty()){
             JOptionPane.showMessageDialog(this, "Data jam tidak boleh kosong");
             txtJam.requestFocus();
             return;
        }
        if (cbGol.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Golongan belum di pilih."
                    + "\nSilahkan pilih Golongan!!");
            return;
        }
        int gol = (int) cbGol.getSelectedIndex();
            int gajiPokok = 0;
            int upahJam = 0;
            
            switch(gol){
                case 1: 
                    gajiPokok = 2000000;
                    upahJam = 20000;
                    break;
                case 2: 
                    gajiPokok = 3000000;
                    upahJam = 30000;
                    break;
                case 3: 
                    gajiPokok = 3750000;
                    upahJam = 40000;
                    break;
                case 4: 
                    gajiPokok = 4500000;
                    upahJam = 50000;
                    break;
                
      
        }
         try{
         int jamKerja = Integer.parseInt(txtJam.getText());
         
         int totalUpah = jamKerja * upahJam;
         int totalGaji = gajiPokok + totalUpah;
         double pajak = totalGaji * 0.025;
         double gajiBersih = totalGaji - pajak;
         
         txtGp.setText(String.valueOf(gajiPokok));
         txtUpj.setText(String.valueOf(upahJam));
         txtTuph.setText(String.valueOf(totalUpah));
         txtTgj.setText(String.valueOf(totalGaji));
         txtPjk.setText(String.valueOf(pajak));
         txtGb.setText(String.valueOf(gajiBersih)); 
         
         
    
}catch (NumberFormatException a){
    JOptionPane.showMessageDialog(this, "Jam kerja harus berupa angka!");
    txtJam.requestFocus();
    

}
     catch (Exception a){
      JOptionPane.showMessageDialog(this, "Terjadi Kesalahan :"+a.getMessage());
}
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNik.setText("");
        txtJam.setText("");
        
        txtGp.setText("");
        txtUpj.setText("");
        txtTuph.setText("");
        txtTgj.setText("");
        txtPjk.setText("");
        txtGb.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
         int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Konfirmasi keluar", JOptionPane.YES_NO_OPTION);
        
        if(pil == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed
     
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromPenggajianKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroupGolongan;
    private javax.swing.JComboBox<String> cbGol;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblGb;
    private javax.swing.JLabel lblGol;
    private javax.swing.JLabel lblGp;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblPenggajian;
    private javax.swing.JLabel lblPjk;
    private javax.swing.JLabel lblTgj;
    private javax.swing.JLabel lblTuph;
    private javax.swing.JLabel lblUpj;
    private javax.swing.JTextField txtGb;
    private javax.swing.JTextField txtGp;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtPjk;
    private javax.swing.JTextField txtTgj;
    private javax.swing.JTextField txtTuph;
    private javax.swing.JTextField txtUpj;
    // End of variables declaration//GEN-END:variables
}
